import type { Meta, StoryObj } from '@storybook/react';
import { OrderDetails } from '../../widgets/OrderDetails/OrderDetails';

const meta: Meta<typeof OrderDetails> = {
  title: 'Widgets/OrderDetails',
  component: OrderDetails,
  parameters: {
    layout: 'padded',
  },
  tags: ['autodocs'],
  argTypes: {
    onDownloadInvoice: { action: 'download invoice' },
    onTrackOrder: { action: 'track order' },
    onCancelOrder: { action: 'cancel order' },
    onReturnOrder: { action: 'return order' },
    onReorder: { action: 'reorder' },
    onContactSupport: { action: 'contact support' },
    onWriteReview: { action: 'write review' },
  },
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Processing: Story = {
  args: {
    orderId: 'ORD-2025-001',
    orderNumber: 'ORD-2025-001',
    orderDate: 'Dec 15, 2025',
    status: 'processing',
    customerName: 'John Doe',
    customerEmail: 'john.doe@example.com',
    customerPhone: '+1 (555) 123-4567',
    shippingAddress: {
      name: 'John Doe',
      addressLine1: '123 Main Street',
      addressLine2: 'Apt 4B',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      phone: '+1 (555) 123-4567',
    },
    items: [
      {
        id: '1',
        name: 'Wireless Bluetooth Headphones',
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=150',
        quantity: 1,
        price: 2999,
        variant: 'Black, Premium',
      },
      {
        id: '2',
        name: 'Smart Watch Pro',
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=150',
        quantity: 1,
        price: 12999,
        variant: 'Silver',
      },
    ],
    subtotal: 15998,
    shippingCost: 99,
    tax: 800,
    discount: 500,
    total: 16397,
    currency: '₹',
    paymentMethod: 'VISA ****1234',
    paymentStatus: 'paid',
    transactionId: 'TXN-7892-2025-12-15',
    estimatedDelivery: 'Dec 20-22, 2025',
    allowCancel: true,
    allowReturn: false,
    allowReorder: true,
  },
};

export const Shipped: Story = {
  args: {
    orderId: 'ORD-2025-002',
    orderNumber: 'ORD-2025-002',
    orderDate: 'Dec 10, 2025',
    status: 'shipped',
    customerName: 'Jane Smith',
    customerEmail: 'jane.smith@example.com',
    customerPhone: '+1 (555) 987-6543',
    shippingAddress: {
      name: 'Jane Smith',
      addressLine1: '456 Oak Avenue',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90001',
    },
    billingAddress: {
      name: 'Jane Smith',
      addressLine1: '789 Pine Street',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90002',
    },
    items: [
      {
        id: '1',
        name: 'Premium Laptop Backpack',
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=150',
        quantity: 2,
        price: 1499,
      },
      {
        id: '2',
        name: 'USB-C Hub 7-in-1',
        image: 'https://images.unsplash.com/photo-1625948515291-69613efd103f?w=150',
        quantity: 1,
        price: 899,
      },
    ],
    subtotal: 3897,
    shippingCost: 0,
    tax: 195,
    discount: 0,
    total: 4092,
    currency: '₹',
    paymentMethod: 'UPI',
    paymentStatus: 'paid',
    transactionId: 'UPI-456-2025-12-10',
    estimatedDelivery: 'Dec 18-19, 2025',
    trackingNumber: 'FDX123456789',
    trackingUrl: 'https://www.fedex.com/track?tracknum=FDX123456789',
    carrier: 'FedEx',
    allowCancel: false,
    allowReturn: false,
    allowReorder: true,
  },
};

export const Delivered: Story = {
  args: {
    orderId: 'ORD-2025-003',
    orderNumber: 'ORD-2025-003',
    orderDate: 'Nov 28, 2025',
    status: 'delivered',
    customerName: 'Mike Wilson',
    customerEmail: 'mike.wilson@example.com',
    customerPhone: '+1 (555) 246-8135',
    shippingAddress: {
      name: 'Mike Wilson',
      addressLine1: '321 Elm Street',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      phone: '+1 (555) 246-8135',
    },
    items: [
      {
        id: '1',
        name: 'Mechanical Keyboard RGB',
        image: 'https://images.unsplash.com/photo-1595225476474-87563907a212?w=150',
        quantity: 1,
        price: 4999,
        variant: 'Blue Switches',
      },
      {
        id: '2',
        name: 'Gaming Mouse Wireless',
        image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=150',
        quantity: 1,
        price: 2499,
      },
      {
        id: '3',
        name: 'Mouse Pad XL',
        image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=150',
        quantity: 1,
        price: 499,
      },
    ],
    subtotal: 7997,
    shippingCost: 150,
    tax: 407,
    discount: 1000,
    total: 7554,
    currency: '₹',
    paymentMethod: 'Credit Card',
    paymentStatus: 'paid',
    transactionId: 'CC-789-2025-11-28',
    deliveredDate: 'Dec 2, 2025',
    trackingNumber: 'DHL987654321',
    trackingUrl: 'https://www.dhl.com/track?tracknum=DHL987654321',
    carrier: 'DHL Express',
    allowCancel: false,
    allowReturn: true,
    allowReorder: true,
  },
};

export const Pending: Story = {
  args: {
    orderId: 'ORD-2025-004',
    orderNumber: 'ORD-2025-004',
    orderDate: 'Dec 19, 2025',
    status: 'pending',
    customerEmail: 'sarah.johnson@example.com',
    shippingAddress: {
      name: 'Sarah Johnson',
      addressLine1: '789 Maple Drive',
      city: 'Austin',
      state: 'TX',
      zipCode: '73301',
    },
    items: [
      {
        id: '1',
        name: 'Organic Cotton T-Shirt',
        quantity: 3,
        price: 799,
        variant: 'Medium, White',
      },
    ],
    subtotal: 2397,
    shippingCost: 99,
    tax: 120,
    discount: 0,
    total: 2616,
    currency: '₹',
    paymentMethod: 'Cash on Delivery',
    paymentStatus: 'pending',
    estimatedDelivery: 'Dec 22-24, 2025',
    allowCancel: true,
    allowReturn: false,
    allowReorder: true,
  },
};

export const Cancelled: Story = {
  args: {
    orderId: 'ORD-2025-005',
    orderNumber: 'ORD-2025-005',
    orderDate: 'Dec 5, 2025',
    status: 'cancelled',
    statusText: 'Cancelled by Customer',
    customerName: 'David Brown',
    customerEmail: 'david.brown@example.com',
    customerPhone: '+1 (555) 369-2580',
    shippingAddress: {
      name: 'David Brown',
      addressLine1: '555 Broadway',
      city: 'Seattle',
      state: 'WA',
      zipCode: '98101',
    },
    items: [
      {
        id: '1',
        name: 'Stainless Steel Water Bottle',
        image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=150',
        quantity: 2,
        price: 599,
        variant: '1 Liter, Blue',
      },
    ],
    subtotal: 1198,
    shippingCost: 0,
    tax: 60,
    discount: 100,
    total: 1158,
    currency: '₹',
    paymentMethod: 'VISA ****5678',
    paymentStatus: 'refunded',
    transactionId: 'REF-123-2025-12-06',
    allowCancel: false,
    allowReturn: false,
    allowReorder: true,
  },
};

export const MultipleItems: Story = {
  args: {
    orderId: 'ORD-2025-006',
    orderNumber: 'ORD-2025-006',
    orderDate: 'Dec 12, 2025',
    status: 'delivered',
    customerName: 'Emma Davis',
    customerEmail: 'emma.davis@example.com',
    shippingAddress: {
      name: 'Emma Davis',
      addressLine1: '123 Tech Park',
      addressLine2: 'Building B, Floor 5',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94105',
      phone: '+1 (555) 789-0123',
    },
    items: [
      {
        id: '1',
        name: 'Wireless Earbuds Pro',
        image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=150',
        quantity: 2,
        price: 1999,
        variant: 'White',
      },
      {
        id: '2',
        name: 'Phone Case Premium',
        image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=150',
        quantity: 2,
        price: 499,
        variant: 'Clear',
      },
      {
        id: '3',
        name: 'Screen Protector',
        quantity: 3,
        price: 299,
      },
      {
        id: '4',
        name: 'USB-C Cable 2m',
        quantity: 4,
        price: 199,
        variant: 'Braided Black',
      },
    ],
    subtotal: 6689,
    shippingCost: 99,
    tax: 334,
    discount: 669,
    total: 6453,
    currency: '₹',
    paymentMethod: 'Apple Pay',
    paymentStatus: 'paid',
    transactionId: 'APL-999-2025-12-12',
    deliveredDate: 'Dec 16, 2025',
    trackingNumber: 'UPS456789123',
    carrier: 'UPS',
    allowCancel: false,
    allowReturn: true,
    allowReorder: true,
  },
};
